services:

  mongodb: 
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - "mongodb:/data/db"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - ./backend/.env
    volumes: 
      - ./backend:/usr/src/app/backend
      #- ./backend/node_modules:/usr/src/app/backend/node_modules
    environment:
     - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/frontend
     # - ./frontend/node_modules:/usr/src/frontend/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes: 
  mongodb:
